---
- hosts: '{{ host_group | default("all") }}'
  gather_facts: false
  tasks:
    - name: ensure packages are up-to-date
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: true

    - name: ensure ca-certificates are up-to-date
      ansible.builtin.apt:
        name: "ca-certificates"
        state: latest
      become: true

    - name: create the directory if it does not exist
      ansible.builtin.file:
        path: ~/cluster
        state: directory
        mode: 0755

    - name: copy secret file
      ansible.builtin.copy:
        src: files/minio_password
        dest: ~/cluster/minio_password
        mode: 0644
      register: secret

    - name: ensure docker-compose.yaml is created
      ansible.builtin.template:
        src: docker-compose.yaml.j2
        dest: ~/cluster/docker-compose.yaml
        mode: 0644
      register: compose_config

    - name: ensure docker-compose services are up
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: ~/cluster
      when: compose_config.changed or secret.changed or force_up | default(false)
